sudo: required

dist: trusty

os:
  - linux

language: bash

services:
 -docker

script:
 -.bundle/
 -bundle exec rake build && bundle exec rake builddoc

notifications:
 email: moustaphasock813@gmail.com
