sudo: required

dist: trusty

os:
  - linux

language: bash

services:
 -docker

gemfile: Gemfile.lock

before_install: bundle install

script: bundle exec build && bundle exec builddoc

notifications:
 email: moustaphasock813@gmail.com
